// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBq0zXQAqSy08G1m1J6jTyxiodVetin78',
    appId: '1:443630856952:web:48fdb1d4b4006d4fb4290d',
    messagingSenderId: '443630856952',
    projectId: 'mars-rover-mission',
    authDomain: 'mars-rover-mission.firebaseapp.com',
    storageBucket: 'mars-rover-mission.appspot.com',
    measurementId: 'G-2KW1WKC2YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNecTVnNV4QjUCY6koqyfK6nTnb6CNAI',
    appId: '1:443630856952:android:3874af079ccad3d3b4290d',
    messagingSenderId: '443630856952',
    projectId: 'mars-rover-mission',
    storageBucket: 'mars-rover-mission.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXMm10TVqF_UxNGuzQnU8sKCMU8qnHXk',
    appId: '1:443630856952:ios:d3f9b56f384b094ab4290d',
    messagingSenderId: '443630856952',
    projectId: 'mars-rover-mission',
    storageBucket: 'mars-rover-mission.appspot.com',
    iosBundleId: 'com.example.marsRoverMission',
  );
}
